INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Administrador', 'ROLE_ADMIN');
INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Cliente', 'ROLE_CLIENTE');

INSERT INTO TB_USUARIO(NOME, EMAIL, SENHA, DATA_CADASTRO) VALUES('José da Silva', 'jose@email.com', '123', NOW());