INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Administrador', 'ROLE_ADMIN');
INSERT INTO TB_PERFIL(DESCRICAO, AUTORIEDADE) VALUES ('Cliente', 'ROLE_CLIENTE');

INSERT INTO TB_USUARIO(NOME, EMAIL, SENHA, DATA_CADASTRO) VALUES('José da Silva', 'jose@email.com', '123', NOW());
INSERT INTO TB_USUARIO_PERFIL(ID_USUARIO, ID_PERFIL) VALUES (1, 1);
INSERT INTO TB_USUARIO_PERFIL(ID_USUARIO, ID_PERFIL) VALUES (1, 2);

INSERT INTO TB_USUARIO(NOME, EMAIL, SENHA, DATA_CADASTRO) VALUES('Marcos da Silva', 'marcos@email.com', '123', NOW());
INSERT INTO TB_USUARIO_PERFIL(ID_USUARIO, ID_PERFIL) VALUES (1, 2);

INSERT INTO TB_CIDADE(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, IBGE, GIA, DDD, SIAFI, DATA_CADASTRO) VALUES ('01451000', 'Avenida Brigadeiro Faria Lima', 'Apartamento', 'Jardim Paulistano', 'São Paulo', 'SP', '3550308', '1004', '11', '7107', NOW());
INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, ID_USUARIO, DATA_CADASTRO) VALUES ('Feira do Software', '2024-05-16', 'https://feiradosoftware.com', 1, 1, NOW());

INSERT INTO TB_CIDADE(CEP, LOGRADOURO, COMPLEMENTO, BAIRRO, LOCALIDADE, UF, IBGE, GIA, DDD, SIAFI, DATA_CADASTRO) VALUES ('01451000', 'Avenida Brigadeiro Faria Lima', 'Apartamento', 'Jardim Paulistano', 'São Paulo', 'SP', '3550308', '1004', '11', '7107', NOW());
INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, ID_USUARIO, DATA_CADASTRO) VALUES ('CCXP', '2024-10-05', 'https://ccxp.com.br', 2, 1, NOW());