INSERT INTO TB_CIDADE(NOME, CODIGO, CREATED_AT) VALUES ('São Paulo', 'SAO_PAULO' ,NOW());
INSERT INTO TB_CIDADE(NOME, CODIGO, CREATED_AT) VALUES ('Rio de Janeiro', 'RIO_DE_JANEIRO', NOW());
INSERT INTO TB_CIDADE(NOME, CODIGO, CREATED_AT) VALUES ('Salvador', 'SALVADOR', NOW());
INSERT INTO TB_CIDADE(NOME, CODIGO, CREATED_AT) VALUES ('Porto Alegre', 'PORTO_ALEGRE', NOW());
INSERT INTO TB_CIDADE(NOME, CODIGO, CREATED_AT) VALUES ('Belo Horizonte', 'BELO_HORIZONTE', NOW());

INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, CREATED_AT) VALUES ('Feira do Software', '2021-05-16', 'https://feiradosoftware.com', 1, NOW());
INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, CREATED_AT) VALUES ('CCXP', '2021-04-13', 'https://ccxp.com.br', 1, NOW());
INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, CREATED_AT) VALUES ('Congresso Linux', '2021-05-23', 'https://congressolinux.com.br', 2, NOW());
INSERT INTO TB_EVENTO(NOME, DATA_EVENTO, URL, ID_CIDADE, CREATED_AT) VALUES ('Semana Spring React', '2021-05-03', 'https://devsuperior.com.br', 3, NOW());