spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/evento-dev?currentSchema=dev
    username: gabriel
    password: gabriel
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    org:
      flywaydb: DEBUG

via:
  cep: https://viacep.com.br/ws/